DELETE FROM COURSE;

INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-1', 10);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-2', 20);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-3', 30);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-4', 40);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-5', 50);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-6', 60);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-7', 70);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-8', 80);
INSERT INTO COURSE (NAME, DURATION) VALUES ('Java-9', 90);